export const ACHIEVEMENTS = [
  // First Steps Chapter
  {
    key: 'first_dose',
    title: 'First Dose Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your very first medication dose',
    lore: 'Every healthy journey starts with one small step.',
    iconName: 'Pill',
    target: 1,
  },
  {
    key: 'first_vital',
    title: 'Vitals Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your first vital reading',
    lore: "Tracking vitals provides the vision to protect your long-term health.",
    iconName: 'Activity',
    target: 1,
  },
  {
    key: 'first_perfect_day',
    title: 'Adherence Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Complete all scheduled medication doses in a single day',
    lore: 'One full day of perfect adherence proves your commitment.',
    iconName: 'Compass',
    target: 1,
  },
  {
    key: 'mood_check_in',
    title: 'Mindful Start',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your mood for the very first time',
    lore: 'Emotional clarity is the foundation of physical vitality.',
    iconName: 'Smile',
    target: 1,
  },

  // Daily Habits Chapter
  {
    key: '3_day_consistent',
    title: 'Consistency Hero',
    tier: 'rare',
    category: 'daily_habits',
    description: 'Maintain an 80%+ medication log rate for 3 consecutive days',
    lore: 'Three consistent days build unbreakable daily momentum.',
    iconName: 'Zap',
    target: 3,
  },
  {
    key: 'never_missed_morning',
    title: 'Morning Guardian',
    tier: 'rare',
    category: 'daily_habits',
    description: 'Take morning medications on time for 3 days',
    lore: 'Starting mornings with purpose sets the tone for your care.',
    iconName: 'Sunrise',
    target: 3,
  },
  {
    key: 'weekly_90',
    title: 'Weekly Adherence Champion',
    tier: 'rare',
    category: 'daily_habits',
    description: 'Maintain 90%+ medication adherence for a full week',
    lore: 'A full week of adherence makes consistency second nature.',
    iconName: 'Target',
    target: 90,
    isPercentage: true,
  },
  {
    key: 'streak_7',
    title: 'Consistency Champion',
    tier: 'rare',
    category: 'daily_habits',
    description: 'Log your vitals or medications for 7 consecutive days',
    lore: 'Seven days of dedicated self-care without missing a beat.',
    iconName: 'Flame',
    target: 7,
  },
  {
    key: 'bp_stabilized',
    title: 'Vitals Guardian',
    tier: 'epic',
    category: 'daily_habits',
    description: 'Maintain stable blood pressure logs for 14 days',
    lore: 'Fourteen days of steady vital tracking strengthens your recovery.',
    iconName: 'HeartPulse',
    target: 14,
  },
  {
    key: 'profile_complete',
    title: 'Health Profile Champion',
    tier: 'rare',
    category: 'daily_habits',
    description: 'Fill in 100% of your health profile information',
    lore: 'A complete medical profile optimizes your care team response.',
    iconName: 'CheckCircle2',
    target: 100,
    isPercentage: true,
  },
  {
    key: 'early_bird',
    title: '???',
    unlockedTitle: 'Early Bird',
    tier: 'rare',
    category: 'daily_habits',
    isHidden: true,
    description: 'Log vitals or medication before 7:00 AM for 7 days',
    lore: 'Taking charge of your health before the world wakes up.',
    iconName: 'Sun',
    target: 7,
  },

  // Milestones Chapter
  {
    key: '7_perfect_days',
    title: 'Perfect Week Champion',
    tier: 'rare',
    category: 'milestones',
    description: 'Log 7 perfect days of 100% medication adherence',
    lore: 'A flawless week of 100% adherence is a masterclass in self-care.',
    iconName: 'Trophy',
    target: 7,
  },
  {
    key: 'night_owl',
    title: 'Night Guardian',
    tier: 'epic',
    category: 'milestones',
    description: 'Log all evening and night doses on time for 5 days',
    lore: 'Quiet evening dedication keeps your care on schedule.',
    iconName: 'Moon',
    target: 5,
  },
  {
    key: 'vitals_tracker',
    title: 'Vitals Champion',
    tier: 'epic',
    category: 'milestones',
    description: 'Log your health vitals on 10 or more days',
    lore: 'Consistent vital monitoring turns data into longevity.',
    iconName: 'HeartPulse',
    target: 10,
  },
  {
    key: 'streak_14',
    title: 'Two-Week Consistency Hero',
    tier: 'epic',
    category: 'milestones',
    description: 'Maintain an 80%+ logging rate for 14 consecutive days',
    lore: 'Two full weeks of relentless consistency builds lasting health.',
    iconName: 'Flame',
    target: 14,
  },
  {
    key: 'monthly_consistent',
    title: 'Consistency Legend',
    tier: 'legendary',
    category: 'milestones',
    description: 'Maintain 80%+ consistency for a full month',
    lore: 'Thirty days of consistent logging transforms actions into lifelong habits.',
    iconName: 'Trophy',
    target: 80,
    isPercentage: true,
  },
  {
    key: 'adherence_30d_90',
    title: 'Medication Guardian',
    tier: 'legendary',
    category: 'milestones',
    description: 'Maintain 90%+ medication adherence over 30 days',
    lore: 'Outstanding dedication to month-long medication recovery.',
    iconName: 'ShieldCheck',
    target: 90,
    isPercentage: true,
  },
  {
    key: 'score_plus_20',
    title: 'Recovery Champion',
    tier: 'legendary',
    category: 'milestones',
    description: 'Improve your overall health score by 20+ points',
    lore: 'A twenty-point score increase is tangible proof of health recovery.',
    iconName: 'TrendingUp',
    target: 20,
  },
  {
    key: '100_doses',
    title: 'Century Champion',
    tier: 'legendary',
    category: 'milestones',
    description: 'Successfully log a total of 100 medication doses',
    lore: 'One hundred doses taken on time is a hundred promises kept to yourself.',
    iconName: 'Medal',
    target: 100,
  },

  // Mastery Chapter
  {
    key: 'streak_30',
    title: 'Consistency Master',
    tier: 'legendary',
    category: 'mastery',
    description: 'Log your medications or vitals for 30 consecutive days',
    lore: 'True mastery is built one daily habit at a time.',
    iconName: 'Crown',
    target: 30,
  },
  {
    key: '30_perfect_days',
    title: 'Adherence Master',
    tier: 'mythic',
    category: 'mastery',
    description: 'Record 30 days of perfect 100% medication adherence',
    lore: 'Pinnacle adherence achieved through relentless daily discipline.',
    iconName: 'Shield',
    target: 30,
  },
  {
    key: 'phoenix_comeback',
    title: '???',
    unlockedTitle: 'Phoenix Comeback',
    tier: 'mythic',
    category: 'mastery',
    isHidden: true,
    description: 'Rebuilt a 7-day streak after missing a previous log',
    lore: 'Rising stronger after a setback proves true resilience.',
    iconName: 'Sparkles',
    target: 7,
  },
];

export const TIER_CONFIG = {
  common: {
    color: '#64748B',
    label: 'Everyday',
    bgColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    gradient: ['#FFFFFF', '#F1F5F9', '#E2E8F0'],
  },
  rare: {
    color: '#7C3AED',
    label: 'Milestone',
    bgColor: '#F5F3FF',
    borderColor: '#DDD6FE',
    gradient: ['#F3E8FF', '#C084FC', '#9333EA'],
  },
  epic: {
    color: '#4F46E5',
    label: 'Elite',
    bgColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    gradient: ['#818CF8', '#4F46E5', '#312E81'],
  },
  legendary: {
    color: '#D97706',
    label: 'Master',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    gradient: ['#FEF08A', '#F59E0B', '#B45309'],
  },
  mythic: {
    color: '#A855F7',
    label: 'Legacy',
    bgColor: '#0F172A',
    borderColor: 'rgba(168, 85, 247, 0.5)',
    gradient: ['#1E293B', '#0F172A', '#581C87'],
  },
  // Backward compatibility mappings
  bronze: { color: '#64748B', label: 'Everyday', bgColor: '#F8FAFC', gradient: ['#FFFFFF', '#F1F5F9'] },
  silver: { color: '#7C3AED', label: 'Milestone', bgColor: '#F5F3FF', gradient: ['#F3E8FF', '#C084FC'] },
  gold: { color: '#D97706', label: 'Master', bgColor: '#FFFBEB', gradient: ['#FEF08A', '#F59E0B'] },
};

export const CATEGORY_CONFIG = {
  first_steps: {
    title: 'First Steps',
    description: 'Beginning your personal health journey',
    iconName: 'Sprout',
    accent: ['#7C3AED', '#C084FC'],
  },
  daily_habits: {
    title: 'Daily Habits',
    description: 'Daily consistency and active vital tracking',
    iconName: 'Calendar',
    accent: ['#6366F1', '#818CF8'],
  },
  milestones: {
    title: 'Milestones',
    description: 'Significant achievements and perfect weeks',
    iconName: 'Trophy',
    accent: ['#D97706', '#FBBF24'],
  },
  mastery: {
    title: 'Mastery',
    description: 'Long-term commitment to lifetime wellness',
    iconName: 'Crown',
    accent: ['#7C3AED', '#A855F7'],
  },
  // Category fallbacks
  building_habits: { title: 'Daily Habits', description: 'Daily consistency', iconName: 'Calendar', accent: ['#6366F1', '#818CF8'] },
  taking_control: { title: 'Daily Habits', description: 'Vital stability', iconName: 'Activity', accent: ['#0891B2', '#22D3EE'] },
  doses: { title: 'Daily Habits', description: 'Doses logged', iconName: 'Pill', accent: ['#6D28D9', '#A78BFA'] },
  streaks: { title: 'Daily Habits', description: 'Streaks', iconName: 'Flame', accent: ['#9F1239', '#F43F5E'] },
  routine: { title: 'Daily Habits', description: 'Routine', iconName: 'Clock', accent: ['#5B21B6', '#C084FC'] },
  wellbeing: { title: 'Daily Habits', description: 'Wellbeing', iconName: 'Activity', accent: ['#7C3AED', '#F3E8FF'] },
  perfect_days: { title: 'First Steps', description: 'Perfect Days', iconName: 'Sprout', accent: ['#7C3AED', '#C084FC'] },
};
