export const ACHIEVEMENTS = [
  // 🌱 First Steps Chapter
  {
    key: 'first_dose',
    title: 'First Dose Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your very first medication dose',
    lore: 'Every journey begins with a single dose. Taking control of your health starts today.',
    iconName: 'Pill',
    target: 1,
  },
  {
    key: 'first_vital',
    title: 'Vitals Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your first vital reading',
    lore: "Tracking your body's vitals gives your care team the vision to protect you.",
    iconName: 'Activity',
    target: 1,
  },
  {
    key: 'first_perfect_day',
    title: 'Adherence Explorer',
    tier: 'common',
    category: 'first_steps',
    description: 'Complete all scheduled medication doses in a single day',
    lore: 'One full day of 100% adherence. You proved to yourself that it is possible.',
    iconName: 'Compass',
    target: 1,
  },
  {
    key: 'mood_check_in',
    title: 'Mindful Start',
    tier: 'common',
    category: 'first_steps',
    description: 'Log your mood for the very first time',
    lore: 'Mental clarity and emotional wellbeing are the foundation of physical health.',
    iconName: 'Smile',
    target: 1,
  },

  // 🏃 Building Habits Chapter
  {
    key: '3_day_consistent',
    title: 'Consistency Hero',
    tier: 'rare',
    category: 'building_habits',
    description: 'Maintain an 80%+ medication log rate for 3 consecutive days',
    lore: 'Three days in a row. Momentum is building.',
    iconName: 'Zap',
    target: 3,
  },
  {
    key: 'never_missed_morning',
    title: 'Morning Guardian',
    tier: 'rare',
    category: 'building_habits',
    description: 'Take morning medications on time for 3 days',
    lore: 'Starting every morning with purpose and precision.',
    iconName: 'Sunrise',
    target: 3,
  },
  {
    key: 'weekly_90',
    title: 'Weekly Adherence Champion',
    tier: 'rare',
    category: 'building_habits',
    description: 'Maintain 90%+ medication adherence for a full week',
    lore: 'A full week of 90%+ compliance. Consistency is becoming second nature.',
    iconName: 'Target',
    target: 90,
    isPercentage: true,
  },
  {
    key: 'streak_7',
    title: 'Consistency Champion',
    tier: 'rare',
    category: 'building_habits',
    description: 'Log your vitals or medications for 7 consecutive days',
    lore: 'Seven consecutive days without missing a single beat.',
    iconName: 'Flame',
    target: 7,
  },
  {
    key: 'early_bird',
    title: '???',
    unlockedTitle: 'Early Bird',
    tier: 'rare',
    category: 'building_habits',
    isHidden: true,
    description: 'Log vitals or medication before 7:00 AM for 7 days',
    lore: 'Sunrise dedication. Taking charge of your health before the world wakes up.',
    iconName: 'Sun',
    target: 7,
  },

  // 🩺 Taking Control Chapter
  {
    key: 'bp_stabilized',
    title: 'Vitals Guardian',
    tier: 'epic',
    category: 'taking_control',
    description: 'Maintain stable blood pressure logs for 14 days',
    lore: '14 days of steady blood pressure logs. Your heart thanks you.',
    iconName: 'HeartPulse',
    target: 14,
  },
  {
    key: 'profile_complete',
    title: 'Health Profile Champion',
    tier: 'rare',
    category: 'taking_control',
    description: 'Fill in 100% of your health profile information',
    lore: 'A complete profile allows emergency response & care team optimization.',
    iconName: 'CheckCircle2',
    target: 100,
    isPercentage: true,
  },
  {
    key: 'hydration_hero',
    title: 'Hydration Champion',
    tier: 'rare',
    category: 'taking_control',
    description: 'Log your hydration levels on 5 different days',
    lore: 'Proper hydration regulates vital organs and speeds recovery.',
    iconName: 'Droplet',
    target: 5,
  },
  {
    key: 'mindful_week',
    title: 'Mindful Champion',
    tier: 'rare',
    category: 'taking_control',
    description: 'Log your mood for 7 days',
    lore: 'A full week of emotional mindfulness and self-checkins.',
    iconName: 'Brain',
    target: 7,
  },

  // 🏆 Major Milestones Chapter
  {
    key: '7_perfect_days',
    title: 'Perfect Week Champion',
    tier: 'legendary',
    category: 'milestones',
    description: 'Log 7 perfect days of 100% medication adherence',
    lore: 'Seven consecutive days of 100% adherence. A flawless week of self-care.',
    iconName: 'Trophy',
    target: 7,
  },
  {
    key: 'night_owl',
    title: 'Night Guardian',
    tier: 'epic',
    category: 'milestones',
    description: 'Log all evening and night doses on time for 5 days',
    lore: 'Evening routine locked in for 5 consecutive nights.',
    iconName: 'Moon',
    target: 5,
  },
  {
    key: 'vitals_tracker',
    title: 'Vitals Champion',
    tier: 'epic',
    category: 'milestones',
    description: 'Log your health vitals on 10 or more days',
    lore: 'Ten days of vital monitoring. Data leads to longevity.',
    iconName: 'HeartPulse',
    target: 10,
  },
  {
    key: 'streak_14',
    title: 'Two-Week Consistency Hero',
    tier: 'epic',
    category: 'milestones',
    description: 'Maintain an 80%+ logging rate for 14 consecutive days',
    lore: 'Two full weeks of relentless daily consistency.',
    iconName: 'Flame',
    target: 14,
  },
  {
    key: 'monthly_consistent',
    title: 'Consistency Legend',
    tier: 'legendary',
    category: 'milestones',
    description: 'Maintain 80%+ consistency for a full month',
    lore: "80%+ consistency over 30 days. You're building a lifetime habit.",
    iconName: 'Trophy',
    target: 80,
    isPercentage: true,
  },
  {
    key: 'adherence_30d_90',
    title: 'Medication Guardian',
    tier: 'legendary',
    category: 'milestones',
    description: 'Maintain 90%+ medication adherence over 30 days',
    lore: '90%+ adherence for a full month. Outstanding dedication to recovery.',
    iconName: 'ShieldCheck',
    target: 90,
    isPercentage: true,
  },
  {
    key: 'score_plus_20',
    title: 'Recovery Champion',
    tier: 'legendary',
    category: 'milestones',
    description: 'Improve your overall health score by 20+ points',
    lore: '20+ point boost in overall health score. Tangible proof of progress.',
    iconName: 'TrendingUp',
    target: 20,
  },
  {
    key: '100_doses',
    title: 'Century Champion',
    tier: 'legendary',
    category: 'milestones',
    description: 'Successfully log a total of 100 medication doses',
    lore: 'One hundred doses taken on time. Every dose is an investment in your future.',
    iconName: 'Medal',
    target: 100,
  },

  // ✨ Legacy & Mastery Chapter
  {
    key: 'streak_30',
    title: 'Consistency Master',
    tier: 'legendary',
    category: 'mastery',
    description: 'Log your medications or vitals for 30 consecutive days',
    lore: '30 consecutive days of logging. True mastery is built one day at a time.',
    iconName: 'Crown',
    target: 30,
  },
  {
    key: '30_perfect_days',
    title: 'Adherence Master',
    tier: 'mythic',
    category: 'mastery',
    description: 'Record 30 days of perfect 100% medication adherence',
    lore: '30 days of 100% perfect adherence. You have reached the pinnacle of self-care.',
    iconName: 'Shield',
    target: 30,
  },
  {
    key: 'phoenix_comeback',
    title: '???',
    unlockedTitle: 'Phoenix Comeback',
    tier: 'mythic',
    category: 'mastery',
    isHidden: true,
    description: 'Rebuilt a 7-day streak after missing a previous log',
    lore: 'Rising stronger after a setback. True champions never stay down.',
    iconName: 'Sparkles',
    target: 7,
  },
];

export const TIER_CONFIG = {
  common: {
    color: '#64748B',
    label: 'White Ceramic',
    bgColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    gradient: ['#FFFFFF', '#F1F5F9', '#E2E8F0'],
  },
  rare: {
    color: '#7C3AED',
    label: 'Purple Crystal',
    bgColor: '#F5F3FF',
    borderColor: '#DDD6FE',
    gradient: ['#F3E8FF', '#C084FC', '#9333EA'],
  },
  epic: {
    color: '#4F46E5',
    label: 'Deep Violet Metal',
    bgColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    gradient: ['#818CF8', '#4F46E5', '#312E81'],
  },
  legendary: {
    color: '#D97706',
    label: 'Royal Gold',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    gradient: ['#FEF08A', '#F59E0B', '#B45309'],
  },
  mythic: {
    color: '#A855F7',
    label: 'Black Obsidian',
    bgColor: '#0F172A',
    borderColor: 'rgba(168, 85, 247, 0.5)',
    gradient: ['#1E293B', '#0F172A', '#581C87'],
  },
  // Backward compatibility mappings
  bronze: { color: '#64748B', label: 'Common', bgColor: '#F8FAFC', gradient: ['#FFFFFF', '#F1F5F9'] },
  silver: { color: '#7C3AED', label: 'Rare', bgColor: '#F5F3FF', gradient: ['#F3E8FF', '#C084FC'] },
  gold: { color: '#D97706', label: 'Legendary', bgColor: '#FFFBEB', gradient: ['#FEF08A', '#F59E0B'] },
};

export const CATEGORY_CONFIG = {
  first_steps: {
    title: '🌱 First Steps',
    description: 'Beginning your personal health journey',
    iconName: 'Sprout',
    accent: ['#7C3AED', '#C084FC'],
  },
  building_habits: {
    title: '🏃 Building Habits',
    description: 'Daily consistency and routine logging',
    iconName: 'Zap',
    accent: ['#6366F1', '#818CF8'],
  },
  taking_control: {
    title: '🩺 Taking Control',
    description: 'Active health improvements & vital stability',
    iconName: 'Activity',
    accent: ['#0891B2', '#22D3EE'],
  },
  milestones: {
    title: '🏆 Major Milestones',
    description: 'Significant logging achievements and perfect weeks',
    iconName: 'Trophy',
    accent: ['#D97706', '#FBBF24'],
  },
  mastery: {
    title: '✨ Legacy & Mastery',
    description: 'Long-term commitment to lifetime wellness',
    iconName: 'Crown',
    accent: ['#7C3AED', '#A855F7'],
  },
  // Legacy mappings fallback
  doses: { title: 'Logging Volume', description: 'Total medication and vitals entries logged', iconName: 'Pill', accent: ['#6D28D9', '#A78BFA'] },
  streaks: { title: 'Consistency & Streaks', description: 'Maintain logs over consecutive days', iconName: 'Flame', accent: ['#9F1239', '#F43F5E'] },
  routine: { title: 'Routine & Adherence', description: 'Time-of-day accuracy and compliance rates', iconName: 'Clock', accent: ['#5B21B6', '#C084FC'] },
  wellbeing: { title: 'Holistic Wellbeing', description: 'Mood, hydration, and overall health tracking', iconName: 'Activity', accent: ['#7C3AED', '#F3E8FF'] },
  perfect_days: { title: 'Perfect Days Progression', description: 'Complete all scheduled medication doses', iconName: 'Star', accent: ['#7C3AED', '#C084FC'] },
};
